### PR TITLE
Displays ORM versions when running tests

### PR DESCRIPTION
**Pull request by zedtux**

### CODE REVIEW

**Comment by alto** [comment]
@zedtux I like the idea. Do you mind merging _master_ back in (resolving any merge conflicts) and making sure the tests pass? Happy to merge afterwards 👍

**Comment by zedtux** [comment]
Sure I'll do it @alto.

**Comment by zedtux** [comment]
@alto I've fixed the conflicts.

**Comment by zedtux** [comment]
@alto can you please have a look?

**Comment by anilmaurya** [comment]
@zedtux Thank you for your contribution 🏅

**Comment by zedtux** [comment]
Thank you for accepting my contribution @anilmaurya 👍

**Pull request merged**
