### PR TITLE
Support for global transition callbacks

### PR DESCRIPTION
**Pull request by alto**
Example:

```ruby
class Job
  include AASM

  aasm do
    state :sleeping, :initial => true, :before_enter => :do_something
    state :running

    after_all_transitions :log_status_change
    ...
  end

  def log_status_change
    puts "changing from #{aasm.from_state} to #{aasm.to_state} (event: #{aasm.current_event})"
  end
end
```

### CODE REVIEW

**Comment by alto** [comment]
This should help with #221 and #253

**Comment by awendt** [comment]
Very nice, thanks for this!

**Comment by nwp** [comment]
This is exactly what I need. When do you plan on releasing 4.4?

**Comment by alto** [comment]
@nwp Released on 2015-10-27 :+1:

**Comment by nwp** [comment]
Thank you so much!

**Pull request merged**
