### PR TITLE
Relocate DslHelper from root namespace to under AASM namespace

### PR DESCRIPTION
**Pull request by yujideveloper**
I relocated `DslHelper` module from the root namespace to under the AASM namespace.
Because it is a module for AASM and should not be located in the root namespace.

### CODE REVIEW

**Comment by yujideveloper** [comment]
CI failed because codecov <= 0.1.20 was yanked from rubygems.org.
I think merging #707 will solve this.

**Comment by anilmaurya** [comment]
@yujideveloper Thank you for your contribution

I merged #707 , can you retry travis build for your PR ?

**Comment by yujideveloper** [comment]
@anilmaurya 
I rebased this PR at master branch and confirmed that passed CI.

**Comment by anilmaurya** [comment]
Thank you for your contribution 👍 @yujideveloper

**Pull request merged**
