### PR TITLE
Add support for MongoMapper

### PR DESCRIPTION
**Pull request by reidmorrison**
This pull request adds support for MongoMapper to AASM.
Thank you for the awesome Gem, we rely on it in production and use it every day.

### CODE REVIEW

**Comment by alto** [comment]
Hi @reidmorrison 

Thanks for your kind words.

Thanks a lot for your pull request, too. It's well written and it includes tests. 

I added two comments though. One tiny one (cleaning up `.gitignore`) and one bigger one (enable `mongoid` tests again. Could you please take a look at those?

After that I'm happy to merge it _AASM_. Support for `mongo_mapper` is highly appreciated!

**Comment by alto** [comment]
Please merge 'aasm/master' back into the pull request (it will lead to some merge conflicts due to updates of the Rails 4.x versions). Sorry for that.

**Comment by alto** [comment]
Ah, and one more thing. Could you please add some lines to the `README` as well? I guess people would like to know about support for `mongo_mapper`.

But I can do that as well. Up to you :+1:

**Comment by reidmorrison** [comment]
Mongoid V4 now uses bson v2 which is not compatible with mongo, the Ruby MongoDB driver, and therefore mongo_mapper.
Had to create separate Gemfiles for Mongoid and MongoMapper after introducing Mongoid V4.

We used to run Mongoid, but due to several production outages with it's replacement to the Mongo Ruby driver called Moped we had to switch to MongoMapper. Production has been completely stable ever since then, and MongoMapper performs very well.
The author for Moped stated that Moped will not be supported once it is replaced in Mongoid by mongo, the official Ruby MongoDB driver.

**Comment by alto** [comment]
Looks good. Thanks a lot for your work. It's very appreciated!

**Comment by alto** [comment]
I just released version `4.1.0` including your changes.

**Comment by reidmorrison** [comment]
Excellent, Thank you.
I will switch my open source gems over to this gem today.

**Pull request merged**
