### PR TITLE
Deep clone state machine during inheritance.

### PR DESCRIPTION
**Pull request by reidmorrison**
Allows child classes to extend the parent state machine without modifying the parents state machine.
Enables https://github.com/aasm/aasm/issues/267

### CODE REVIEW

**Comment by reidmorrison** [comment]
@alto any thoughts on this one?

It is a critical capability needed before I can release V2 of [rocketjob](http://rocketjob.io). It allows child jobs to add their own callbacks to aasm state machines defined in parent classes. These callbacks are a major feature of this release. See: https://github.com/rocketjob/rocketjob/blob/v2.0/lib/rocket_job/concerns/event_callbacks.rb

Let me know if you have any suggestions, or a better way to expose callbacks for child classes than the above code.

**Comment by alto** [comment]
@reidmorrison Sorry for coming back to you so late.

No, the PR actually looks pretty good. Only concern I have is that you didn't test that by changing the state machine of the subclass you didn't change the state machine of the superclass, too. Could you add that? I'm a happy PR merger then :+1:

**Comment by alto** [comment]
@reidmorrison Thanks for your recent commit. Could you please add a test covering that fix?

**Comment by Tybot204** [comment]
@alto @reidmorrison I added the tests ensuring the superclass  is not modified in a new PR here: https://github.com/aasm/aasm/pull/429

**Comment by reidmorrison** [comment]
Closing this PR in favor of https://github.com/aasm/aasm/pull/429

**Pull request closed without merging**
