### PR TITLE
Patch `allow_event` to accept event with custom arguments

### PR DESCRIPTION
**Pull request by czhc**
Pass arguments for `event` hooks, similar to `on_event` for `state` hooks.

### CODE REVIEW

**Comment by czhc** [comment]
@anilmaurya can I help your help to review this PR?

**Comment by sbayona** [comment]
Curious to know why this hasn't been merged. Anything I can help with?

**Comment by anilmaurya** [comment]
Thank you @czhc for contributing 🏅
Thank you @sbayona for reminding 😊

**Comment by czhc** [comment]
💐  sweet, thanks guys

**Pull request merged**
