### PR TITLE
Use a symbol as the name of AR callback instead of block

### PR DESCRIPTION
**Pull request by sineed**

### CODE REVIEW

**Comment by sineed** [comment]
Hi.

Thanks for `aasm` gem. I use it in my project and find it very useful.
I have some cases when I have an AR object that is not prepared for state machine usage. So I don't want to use the callback defined an AR persistence file and want to skip it:

```ruby
class MyClass
  include AASM
  
  skip_callback :initialize, :after, :aasm_ensure_initial_state
end
```

But now I can't do like that because I need to find an object id of proc object which I find really hard.

This PR solves my problem.

**Comment by alto** [comment]
@sineed Sounds reasonable. Thanks!

**Comment by alto** [comment]
I just released version `4.10.0` including your changes.

**Comment by csmuc** [comment]
In my case (retrieving many records in an API) the method-based approach is also significantly faster than the old proc version. `Benchmark.ips` shows 22.6 requests/s vs. 20.8 requests/s.

Actually I would like to skip this callback altogether when simply loading stuff from the DB for rendering (23.4 requests/sec when I remove the callback).

**Pull request merged**
