### PR TITLE
Fixes #709 : Remove memoization to avoid stale localized state name

### LINKED ISSUE #709: human_state cached across locales in 5.1.1 release
**Describe the bug**
The method aasm.human_state returns the state name using a translation. Once returned for one locale, the same text is subsequently returned for other locales too.

**To Reproduce**
Steps to reproduce the behaviour:
``````
    it 'shows text in 2 different locales' do
      ep = described_class.new
      I18n.locale = :fr
      fr_text = ep.aasm.human_state
      I18n.locale = :de
      de_text = ep.aasm.human_state
      expect(fr_text).not_to eq(de_text)
    end
``````
**Expected behavior**
I would expect the above spec to pass
**Screenshots**
n/a

**Additional context**
I have only tested this in the context of our application.

### PR DESCRIPTION
**Pull request by the-spectator**
Fixes #709

Remove memoization to avoid stale localized state name

### CODE REVIEW

**Comment by anilmaurya** [comment]
Hi @the-spectator 

A spec verifying bug fix will be good to have.

**Comment by the-spectator** [comment]
@anilmaurya Added specs. Please have a look at it.

**Comment by anilmaurya** [comment]
Great @the-spectator , thank you for contributing 🏅

**Comment by the-spectator** [comment]
@anilmaurya will it be alright if this PR to get labeled as `hacktoberfest-accepted` ?

**Comment by anilmaurya** [comment]
Done @the-spectator

**Pull request merged**
