### PR TITLE
Enable AASM scopes to be defined on abstract classes

### PR DESCRIPTION
**Pull request by RickCSong**
Currently, if aasm is called on an abstract class, the scopes are not
properly defined because it infers the table_name at time of creation.
This change pushes the inference of table_name to when the scope is
called which enables scopes to be dynamically defined in descendant
models.

### CODE REVIEW

**Comment by anilmaurya** [comment]
Hi @RickCSong .
Thank you for fixing this issue. Can you help with fixing travis build ?

**Comment by RickCSong** [comment]
Fixed!  Thank you.  Just found out that scopes on abstract classes didn't work until ActiveRecord 5. Added a comment.

**Comment by RickCSong** [comment]
Hey there @anilmaurya !  Any chance you may be able to take another look at this?

**Comment by anilmaurya** [comment]
Thanks @RickCSong 👍

**Pull request merged**
