### PR TITLE
Transition success callbacks

### PR DESCRIPTION
**Pull request by brega**
Tentative PR with regards to #236 

Open to feedback on direction and validity of use-case.

### CODE REVIEW

**Comment by alto** [comment]
@brega Thanks for the pull request. It looks good so far.

Let's keep the discussion about it in #236 .

**Comment by alto** [comment]
@brega Sorry for coming back to this so late. I thought about it again and I'm very happy to merge it. Which I did (and resolving any conflicts time has brought).

**Comment by brega** [comment]
Great, thanks @alto

**Comment by alto** [comment]
I just released version `4.10.0` including your changes.

**Pull request merged**
