### PR TITLE
Create named scope for each state name

### PR DESCRIPTION
**Pull request by evheny0**
This fix is related to #365

### CODE REVIEW

**Comment by anilmaurya** [comment]
@evheny0 Thank you for your contribution. Can you please add a spec to make sure we don't break this in future.

**Comment by evheny0** [comment]
@anilmaurya done :+1:

**Comment by anilmaurya** [comment]
@evheny0 Thank you , I appreciate your help ♡

**Comment by anilmaurya** [comment]
@evheny0 I released `4.11.1` including your changes.

**Pull request merged**
