### PR TITLE
Use appraisal to test all the matrix locally

### LINKED ISSUE #334: [Feature Request] Add Appraisal (https://github.com/thoughtbot/appraisal)
I found it difficult to test aasm for different versions of dependencies.

To run specs for different gemfile on local machine I copied respective gemfile to root Gemfile, did bundle install and then run specs. I had to repeat these steps for all gemfiles for which I want to run my specs.

I think adding `appraisal` gem will simplify this. If you know of any better way than please let me know.

### PR DESCRIPTION
**Pull request by pirj**
Fixes #334

### CODE REVIEW

**Comment by alto** [comment]
@pirj I'm new to [Appraisal](https://rubygems.org/gems/appraisal). I checked out your branch and tried it out:

```sh
bundle install
# installed appraisal

rake
# >> BUNDLE_GEMFILE=/Users/alto/workspace/aasm/gemfiles/rails_3.2_stable.gemfile bundle exec rake
# The git source git://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application

# as described in TESTING.md:
appraise rails_4.2 rspec
# appraise: command not found

# as described in the Appraisal README:
appraisal rails_4.2 rspec
# Could not find gem 'rails (= 4.2.5) ruby' in the gems available on this machine.
# Run `bundle install` to install missing gems.

# another try with a lot
appraisal rspec
# >> BUNDLE_GEMFILE=/Users/alto/workspace/aasm/gemfiles/rails_3.2_stable.gemfile bundle exec rspec
# The git source git://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application
```

What am I doing wrong?

**Comment by pirj** [comment]
@alto I'm new to appraisal too. It seems that you missed the part with `appraise install` which installs all the gems for each specific test gem set. This is not transparent to future aasm contributors unfamiliar with appraisal and needs a warning or something.

**Comment by alto** [comment]
@pirj I see. Will try it out. Cheers!

**Comment by anilmaurya** [comment]
@pirj I would love to merge this pull request. Sorry for late response, somehow I missed this pull request.

Please resolve conflict and we are good to go :+1:

**Comment by pirj** [comment]
Sorry for the delay. Rebased and polished a bit.

Regarding `redis-objects`, should we be testing against it in all the gemfiles? I doubt it will significantly slow testing down and there's doubtfully anyone working on AASM on a machine lacking Redis.

Note: had to extract mongoid_4 build because of earlier bundler (on ruby 1.9) not aware of ruby platforms higher than 2.1, and it's impossible to use `:platform =>` with 2.2 and 2.3 in Gemfile.

There's still room for improvment, e.g. I don't see a reason to test both rails_4.2.gemfile and rails_4.2_mongoid_5.gemfile on same platform, later should be sufficient.

Also it would be cool to re-generate gemfiles on travis side, but this might fail when test still pass on an dev machine with stall gemfiles. I'd add a policy to re-generate gemfiles when changing Appraise file, and never allow direct edits to gemfiles, however I don't have an idea how to enforce it.

**Comment by anilmaurya** [comment]
@pirj Thank you for your work. Unfortunately I am very busy for next 3-4 weeks therefore I won't be able to review your changes. Meanwhile if @alto can have a look then its good else I will get back to this pull request after few weeks.

**Comment by pirj** [comment]
Hey @anilmaurya, have you had a chance to look at this one? I've improved the PR compared to initial submission and feel it's pretty safe to merge. PLMK if there should be more clarifications for contributors on how to run test suite or anything else.

**Comment by anilmaurya** [comment]
Hi @pirj , I will look at this PR on coming weekend. Thank you for reminder :)

**Comment by anilmaurya** [comment]
Thank you @pirj for your contribution 🏄🏻

**Pull request merged**
