### PR TITLE
Get rid of unneded activesupport base ext dep

### PR DESCRIPTION
**Pull request by tristandruyen**
This PR get's rid of the undocumented & unrequired activesupport dependency discovered in #508 by using builtin ruby stuff instead of activesupports `.blank?`

### CODE REVIEW

**Comment by tristandruyen** [comment]
One could also solve this issue by explicitly adding activesupport to the gemsec and requiring blank...
I don't think this is needed as it's only used in a few places and was easy to replace.

**Comment by anilmaurya** [comment]
Hi @tristandruyen 
Thank you for sending PR. I am wondering if we can write a spec to prevent using `blank?` in future.
what do you think ?

**Comment by tristandruyen** [comment]
Sorry for the force-push fuckup...

I just added an appraisal which explicitly does not install rails.
You can see it fail here:(https://travis-ci.org/tristandruyen/aasm/builds/533703927)

It should fail when any core extensions added by rails is used, not just `blank?`, so this seems the safest way to test this IMO.

**Comment by anilmaurya** [comment]
Great 🏆

Thank you, I Appreciate your contribution. ♡
I will merge this PR after travis build passes.

**Comment by tristandruyen** [comment]
Awesome! Thanks for the quick merge 👍 
Could you please publish a new version when you find the time.
Thx alot 🥇

**Comment by anilmaurya** [comment]
Yes, will release new version soon.

**Comment by anilmaurya** [comment]
Released new version `5.0.5`

**Pull request merged**
