### PR TITLE
Add [dynamoid](http://joshsymonds.com/Dynamoid/) support.

### PR DESCRIPTION
**Pull request by LeeChSien**
Hi, I'm using AWS Dynamodb with gem Dynamoid, so I tried to integrate AASM with Dynamoid.

If there are any problem in my patch, please let me know.

Thanks a lot for AASM.

### CODE REVIEW

**Comment by alto** [comment]
@LeeChSien Thanks a lot for your PR. Could you please make sure it's tested using Travis CI?

**Comment by LeeChSien** [comment]
@alto Hi,  I just add Dynamodb-local on Travis CI, and passed the test, but I didn't install Dynamoid and run my tests in rails_3.2 due to dependency issue, Thanks.

**Comment by alto** [comment]
@LeeChSien Great work! Happy to merge.

**Comment by alto** [comment]
I just released version `4.8.0` including the change.

**Pull request merged**
