### PR TITLE
:pencil: fix typo

### PR DESCRIPTION
**Pull request by jaredsmithse**

### CODE REVIEW

**Comment by alto** [comment]
Uhm, do you think that's a typo?

**Comment by jaredsmithse** [comment]
It seemed like it, so i made a suggestion for the edit.

**Comment by alto** [comment]
Hmm, allright, I just talked to a friend of mine, a native English speaker. And he said, it should be "automatic" instead. Do you agree? (reason is, I don't think it has any magic in it ;) )

**Comment by jaredsmithse** [comment]
Thats fine. Neither the original or my suggestion is a real word I think, but 'automagical' is sometimes used in Ruby (more specifically Rails) to describe some things that are automatically done for you in a way that seems like magic. 

Completely looked over what the normal english word should be :stuck_out_tongue:

**Comment by alto** [comment]
Lovely! Thanks a lot!

**Pull request merged**
