### PR TITLE
Add use transaction flag (README pending)

### PR DESCRIPTION
**Pull request by lichtamberg**
I've added a flag wrapping of transactions with ActiveRecord.. See also #431 
Please let me know if this is fine and I will add more README stuff.

### CODE REVIEW

**Comment by anilmaurya** [comment]
@lichtamberg Thank you for contributing to AASM, I will review this PR soon. 👍

**Comment by lichtamberg** [comment]
Did you already have time to review it?

**Comment by anilmaurya** [comment]
@lichtamberg I will try to spare some time, in the meantime can you please resolve conflicts with master branch.

**Comment by mbramson** [comment]
Does anyone know where this PR stands? This is something that I would love to be a part of AASM as the requires_new_transactions config doesn't seem to accomplish what I need despite initially looking like it should.

On a side note, perhaps this PR should include an update to the README documenting this flag?

**Comment by mbramson** [comment]
@lichtamberg (and @anilmaurya) as I would like to move this along quickly, do you object to me cherry-picking your commit and resolving the merge conflicts and adding this feature to the README in my own PR?

**Comment by lichtamberg** [comment]
@mbramson No sure, go ahead! Thank you!

**Comment by anilmaurya** [comment]
@lichtamberg Sorry , I forgot to look at his PR. This PR looks good to me .

@mbramson Awaiting your pull request with Readme update. Thank you.

**Comment by mbramson** [comment]
New PR is here: https://github.com/aasm/aasm/pull/493

**Comment by lichtamberg** [comment]
Nice, thank you very much!

**Comment by erictrue** [comment]
Very cool. Do you have a guess about when the next gem will be pushed?

**Comment by anilmaurya** [comment]
@erictrue I will release a new version with this change very soon.

**Pull request closed without merging**
