### PR TITLE
[RubyMotion support] Fixing some issues with Proc based guardians and callbacks.

### PR DESCRIPTION
**Pull request by Infotaku**
Spotted an issue due to RubyMotion's Proc implementation.

Proc does not have the method 'parameters' nor 'source_location'.
This was going to be a pain in my ass until I discovered that Proc's 'arity' method had a different behavior in Ruby and RubyMotion.. at my advantage !
I had to sacrify some debugging 'hints' for us RubyMotion developers to achieve the fix, but nothing too hard.

### CODE REVIEW

**Comment by Infotaku** [comment]
I just saw that you have a PR (https://github.com/aasm/aasm/pull/316) that adds some logic to the same method. 
By what I see in the edited files, this PR will re-break RubyMotion support (use of 'source_location').

Please tell me if you need me to make a pass on that logic to bring RubyMotion support back after the merge.

**Comment by alto** [comment]
@Infotaku Thanks for your work on this. I will let you know once #316 is merged into _master_ (and before I release it).

**Comment by alto** [comment]
@Infotaku I just merged #316 into _master_. Please have a look! I will release it once you say it's okay for you.

**Comment by alto** [comment]
I just released version `4.9.0` including the change.

**Pull request merged**
