### PR TITLE
Sequel transactions

### PR DESCRIPTION
**Pull request by Aryk**
Addresses ticket: #474.

I did a little bit of refactoring because there were multiple instances of repeated code. All the persistence classes are much smaller and behavior in the gem can be modified more easily through AASM::Persistence::ORM for Persistence modules that are orm-like.

I tested all the specs for ActiveRecord, Sequel, and Mongoid. I didn't touch other ORMs so didn't feel the need to install a bunch of extra stuff I don't use.

Nevertheless, the CI system here tested the rest and everything passes.

@anilmaurya - please take a look.

### CODE REVIEW

**Comment by Aryk** [comment]
@anilmaurya - Fixed the dynamoid spec bug, should be all set now.

**Comment by Aryk** [comment]
@anilmaurya - did you have a chance to look at this one?

**Comment by anilmaurya** [comment]
@Aryk Thank you for sending PR, currently I am short of time therefore not able to review this PR.

Give me some time, I'll come back to this PR soon.

**Comment by Aryk** [comment]
Thanks @anilmaurya! 👍 

Looking forward to getting back on the master branch! 😃

**Comment by Aryk** [comment]
Hey @anilmaurya, just wanted to check in on this. Any idea when you might be able to take a look?

**Comment by anilmaurya** [comment]
@Aryk Thank you for reminding, I will try to look at this PR soon .

**Comment by Aryk** [comment]
hey @anilmaurya, how's it lookin' ?

**Comment by anilmaurya** [comment]
@Aryk Thank you for contributing and reminding me again ♡

**Comment by Aryk** [comment]
you're welcome thanks for merging it! I hope it helps get more adoption with folk using other ORMs.

**Comment by Aryk** [comment]
Just curious, when will this get into the next release?

**Comment by Aryk** [comment]
hey @anilmaurya, just curious if I should just pull from the master branch or if there is a new release going to come up?

thanks in advance.

**Comment by anilmaurya** [comment]
@Aryk New release is coming up soon.

**Comment by anilmaurya** [comment]
@Aryk AASM `4.12.1` is released with your changes . 🏄🏻

**Pull request merged**
