### PR TITLE
Fix rails generator

### PR DESCRIPTION
**Pull request by long-long-float**

### CODE REVIEW

**Comment by anilmaurya** [comment]
@long-long-float Is there anything broke with AASM rails generator ? Or its just cosmetic changes .

**Comment by long-long-float** [comment]
Both.

When I executed following commands, an error was occurred like `uninitialized constant AddAasmStateToDocument`.

```
$ rails g aasm Document
$ rake db:migrate
```

And [up/down method is the old style](http://guides.rubyonrails.org/active_record_migrations.html#using-the-up-down-methods).

**Comment by alto** [comment]
@anilmaurya Did you ever experience anything like what @long-long-float describes (`uninitialized constant`)?

**Comment by anilmaurya** [comment]
@alto No, I never faced this issue.
@long-long-float please mention steps to reproduce this issue.

**Comment by long-long-float** [comment]
```shell
$ rails -v
Rails 4.2.5.1
$ rails new test-app --skip-bundle
# generating files...
$ cd test-app
$ echo "gem 'aasm'" >> Gemfile
$ bundle install --path vendor/bundle
# installing gems...
$ bundle exec rails g model Document
$ bundle exec rails g aasm Document
$ bundle exec rake db:migrate
== 20160319051516 CreateDocuments: migrating ==================================
-- create_table(:documents)
   -> 0.0029s
== 20160319051516 CreateDocuments: migrated (0.0031s) =========================

rake aborted!
NameError: uninitialized constant AddAasmStateToDocuments
# ...snip...
```

**Comment by anilmaurya** [comment]
@long-long-float thank you for responding quickly.
@alto Unfortunately I am on vacation for 1 week and can't confirm the error or debug it right now.

**Comment by alto** [comment]
@anilmaurya No worries. No need to rush things. Thanks for helping on this!

**Comment by anilmaurya** [comment]
@alto I confirm this Bug. Please merge this pull request.
@long-long-float Thank you for fixing it.

**Comment by alto** [comment]
I just released version `4.10.0` including your changes.

**Pull request merged**
