### PR TITLE
automatically set timestamps on state update #418

### PR DESCRIPTION
**Pull request by CapCap**
an attempt at #418

### CODE REVIEW

**Comment by reidmorrison** [comment]
Rather than building the `timestamp` capability directly into every persistence layer supported by AASM, could the `timestamp` mechanism generate a callback under the covers that calls the setter for the column?

This will also keep more advanced logic out of every persistence layer so that they can focus purely on persistence.

By enabling the global timestamp config, will it break any gems that the application uses that also use AASM, but do not have any timestamps?

**Comment by anilmaurya** [comment]
@reidmorrison comment sounds good to me, @CapCap @Drenmi What do you guys think ?

**Comment by Drenmi** [comment]
Sounds like a sensible approach @reidmorrison. 🙂

**Comment by CapCap** [comment]
@reidmorrison I like it too. Not sure how much time I have to do it though, but will try

**Comment by pynixwang** [comment]
what callback should I use to set timestamp column?

**Comment by pynixwang** [comment]
before is ok

**Pull request closed without merging**
