### PR TITLE
Add generators to configure active_record and mongoid after install

### PR DESCRIPTION
**Pull request by anilmaurya**
- Added command `rails generate aasm NAME [COLUMN_NAME]`

- https://github.com/aasm/aasm/issues/205

### CODE REVIEW

**Comment by alto** [comment]
@anilmaurya  Thanks for this pull request. I added some comments. Could you please make sure that the _Travis CI_ build runs through?

**Comment by anilmaurya** [comment]
@alto I have fixed generator specs and changed namespace from Aasm to AASM.

One Job (https://travis-ci.org/aasm/aasm/jobs/53452852) is failing with error message:
 The command "bundle exec rake" exited with 1.

**Comment by anilmaurya** [comment]
@alto one build is failing because Rails 3 is not supported anymore for ruby 2.2 https://github.com/rails/rails/issues/18201

However upgrading rails 3.2.21 to rails 3-2-stable may solve this issue (https://github.com/rails/rails/pull/18306)

**Comment by alto** [comment]
@anilmaurya Do you mind checking the merge conflicts (between your branch and _AASM_'s current master)? I would then happily merge your pull request. :+1:

**Comment by anilmaurya** [comment]
@alto ok, I will resolve conflict and let you know.

**Comment by alto** [comment]
@anilmaurya Thank you!

**Comment by anilmaurya** [comment]
Closing this pull request, created new https://github.com/aasm/aasm/pull/261

**Pull request closed without merging**
