### PR TITLE
[RubyMotion support] Maintaining support after PR #316

### PR DESCRIPTION
**Pull request by Infotaku**
Here is the update to ensure RubyMotion support after merging PR https://github.com/aasm/aasm/pull/316.

### CODE REVIEW

**Comment by Infotaku** [comment]
I'm having a hard time figuring out where the failure is taking place for the failed travis build, is there a way to have a more detailed backtrace ?

**Comment by alto** [comment]
@Infotaku Thanks for taking of this!

**Comment by Infotaku** [comment]
Oh I didn't even realise my latest commit had been pushed here, I'm happy it fixed the issue !

I'm still trying to figure out if I should push or unshift the sources into the RubyMotion app files.

I'll edit the README when I'm done.

**Comment by alto** [comment]
I just released version `4.10.0` including your changes.

**Pull request merged**
